version: '3.8'

services:
  nginxproxymanager:
    image: jc21/nginx-proxy-manager:latest
    container_name: nginx-proxy-manager
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "81:81"
    volumes:
      - npm_data:/data
      - npm_letsencrypt:/etc/letsencrypt
    networks:
      - app-network

  backend:
    build: ./backend
    container_name: backend
    restart: always
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    expose:
      - "8080"
    networks:
      - app-network

  frontend:
    build: ./frontend
    container_name: frontend
    restart: always
    expose:
      - "80"
    networks:
      - app-network

volumes:
  npm_data:
  npm_letsencrypt:

networks:
  app-network:
    driver: bridge