version: '3.9'

services:

  backend:
    build: ./backend
    container_name: backend
    restart: always
    expose:
      - "8080"   # expose cho Nginx Proxy, không phải publish
    environment:
      SPRING_PROFILES_ACTIVE: prod
    networks:
      - app-network

  frontend:
    build: ./frontend
    container_name: frontend
    restart: always
    environment:
      - VIRTUAL_HOST=v2.slmglobal.vn
      - LETSENCRYPT_HOST=v2.slmglobal.vn
      - LETSENCRYPT_EMAIL=admin@slmglobal.vn
    volumes:
      - frontend_dist:/usr/share/nginx/html:ro
    networks:
      - app-network

  nginx:
    image: nginx:1.27
    container_name: nginx
    restart: always
    depends_on:
      - frontend
      - backend
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - frontend_dist:/usr/share/nginx/html:ro
    expose:
      - "80"
    environment:
      - VIRTUAL_HOST=v2.slmglobal.vn
    networks:
      - app-network

volumes:
  frontend_dist:

networks:
  app-network:
